2019-06-26 15:04:00 [base WARNING] Not Found: /favicon.ico
2019-06-26 15:04:01 [base WARNING] Not Found: /sys_center_m$
2019-06-26 15:07:41 [base WARNING] Not Found: /admin
2019-06-26 15:20:21 [exception ERROR] Internal Server Error: /sys_center_m
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'view_block'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "E:\xpm\apps\manager\xadmin\sites\views\custom_view.py", line 18, in get
    return render(request, 'cso/xadmin/base_site.html', context)  # 最后指定自定义的template模板，并返回context
  File "F:\workspace\cso_venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'view_block', expected 'endblock'. Did you forget to register or load this tag?
2019-06-26 15:41:59 [exception ERROR] Internal Server Error: /tset_echarts
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "E:\xpm\apps\manager\xadmin\sites\views\custom_view.py", line 29, in get
    return render(request, 'cso/xadmin/audit/echarts_show.html', context)  # 最后指定自定义的template模板，并返回context
  File "F:\workspace\cso_venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 5: 'static', expected 'endblock'. Did you forget to register or load this tag?
2019-06-26 16:47:11 [base WARNING] Not Found: /pydash/
2019-06-26 16:47:35 [base WARNING] Not Found: /pydash/
2019-06-26 16:47:37 [base WARNING] Not Found: /pydash/
2019-06-26 16:47:45 [base WARNING] Not Found: /pydash/index
2019-06-26 16:48:01 [base WARNING] Not Found: /pydash/
2019-06-26 16:48:11 [base WARNING] Not Found: /pydash/
2019-06-26 16:48:49 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:48:49 [exception ERROR] Internal Server Error: /pydash/info/memory/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 325, in memusage
    datasets_free.append(int(mem_usage['free']))
TypeError: string indices must be integers
2019-06-26 16:48:49 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:48:50 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:48:54 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:48:54 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:48:54 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:48:55 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:48:56 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:48:56 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:48:58 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:48:58 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:00 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:00 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:02 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:02 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:04 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:04 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:06 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:06 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:08 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:08 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:10 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:10 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:12 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:12 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:14 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:14 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:16 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:16 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:18 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:18 [exception ERROR] Internal Server Error: /pydash/info/memory/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 325, in memusage
    datasets_free.append(int(mem_usage['free']))
TypeError: string indices must be integers
2019-06-26 16:49:18 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:19 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:20 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:20 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:22 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:22 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:24 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:24 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:26 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:26 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:28 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:28 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-06-26 16:49:30 [exception ERROR] Internal Server Error: /pydash/info/gettraffic/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 512, in gettraffic
    datasets_in_i.append(float(traffic['traffic_in']))
TypeError: 'int' object is not subscriptable
2019-06-26 16:49:30 [exception ERROR] Internal Server Error: /pydash/info/getdiskio/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\xpm\apps\pydash\views.py", line 634, in getdiskio
    datasets_in_i.append(int(diskrw[1]))
IndexError: string index out of range
2019-07-02 16:11:22 [base WARNING] Not Found: /favicon.ico
2019-07-02 16:17:32 [exception ERROR] Internal Server Error: /agent/snmphostdata/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "F:\workspace\cso_venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "F:\workspace\cso_venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "F:\workspace\cso_venv\lib\site-packages\django\template\loader_tags.py", line 122, in get_parent
    raise TemplateSyntaxError(error_msg)
django.template.exceptions.TemplateSyntaxError: Invalid template name in 'extends' tag: ''. Got this from the 'base_template' variable.
2019-07-02 16:30:20 [base WARNING] Not Found: /favicon.ico
2019-07-02 16:39:22 [exception ERROR] Internal Server Error: /manager/infosecevent/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\list.py", line 405, in get
    context = self.get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\list.py", line 387, in get_context
    context = super(ListAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 510, in get_context
    context = super(ModelAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 405, in get_context
    context = super(CommAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 60, in _inner_method
    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
xadmin.views.base.IncorrectPluginArg: Plugin filter method need a arg to receive parent method result.
2019-07-02 16:39:56 [exception ERROR] Internal Server Error: /manager/infosecevent/
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\list.py", line 405, in get
    context = self.get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\list.py", line 387, in get_context
    context = super(ListAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 510, in get_context
    context = super(ModelAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 56, in _inner_method
    result = func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 405, in get_context
    context = super(CommAdminView, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  [Previous line repeated 2 more times]
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 60, in _inner_method
    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
xadmin.views.base.IncorrectPluginArg: Plugin filter method need a arg to receive parent method result.
2019-07-02 16:58:55 [base WARNING] Not Found: /test_bootstrp_table$
2019-07-02 17:19:23 [exception ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\workspace\cso_venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\anaconda\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\dashboard.py", line 593, in get
    return self.template_response('xadmin/views/dashboard.html', self.get_context())
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\dashboard.py", line 586, in get_context
    context = super(Dashboard, self).get_context()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 410, in get_context
    menus = copy.copy(self.get_nav_menu())
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "F:\workspace\cso_venv\lib\site-packages\xadmin\views\base.py", line 336, in get_nav_menu
    site_menu = list(self.get_site_menu() or [])
  File "E:\xpm\apps\manager\xadmin\sites\nav_menu_lists.py", line 48, in get_site_menu
    if self.request.user.is_superuser():
TypeError: 'bool' object is not callable
2019-07-02 17:19:24 [base WARNING] Not Found: /favicon.ico
